"""file_audit / probes の結果から Markdown レポートを組み立てる（日英対応）。"""
from __future__ import annotations

import datetime

from ..audit.conversion import ChatTemplateDiff, ProbeDiff
from ..probes.runner import ProbeReport

CATEGORY_LABELS_JA = {
    "instruction-override": "指示上書き",
    "roleplay-jailbreak": "ロールプレイ脱獄",
    "harmful-code-generation": "有害コード生成",
    "data-leak-elicitation": "データ漏洩誘導",
    "prompt-injection-in-content": "プロンプトインジェクション（コンテンツ内埋め込み）",
    "privilege-escalation": "権限昇格・社会工学",
    "illegal-activity-instructions": "違法行為の指南",
    "system-prompt-extraction": "システムプロンプト抽出",
    "pretext-exercise": "口実（演習・創作を装う）",
    "prefill-injection": "思考・応答の注入（プレフィル）",
}

_STRINGS = {
    "ja": {
        "title": "セキュリティー監査情報",
        "generated_by_date": "{date}時点でのmodel-audit-liteによる自動監査結果です。",
        "file_audit_heading": "## 配布物としての安全性監査",
        "pickle_check_label": "**pickle形式チェック**",
        "pickle_found": (
            "⚠️ pickle形式のファイルが検出されました: {files}\n"
            "  任意コード実行のリスクがあります。内容を確認するか、safetensors形式への変換を検討してください。"
        ),
        "pickle_clean": "pickle形式（`.bin`/`.pt`/`.pth`/`.pkl`など）は検出されませんでした。",
        "code_check_label": "**同梱コードチェック**",
        "code_found": "このリポジトリには独自のPythonコード（{files}）が同梱されています。モデルを利用する前に内容をご確認ください。",
        "code_clean": "`trust_remote_code`が必要なカスタムPythonコードは検出されませんでした。",
        "checksums_label": "**チェックサム (SHA256)**",
        "probe_heading": "## 簡易安全性テスト（プロンプトインジェクション/データ漏洩）",
        "probe_intro": "既知の代表的な攻撃パターン{n}件による簡易テストの結果です。",
        "table_header": "| ID | カテゴリ | ヒューリスティック判定 |\n|---|---|---|",
        "summary": "**{n}件中{safe}件が安全側の挙動でした。**",
        "notes_heading": "### 重要な注意事項（必ずお読みください）",
        "notes": [
            "これは**限定的な既知パターンによる簡易チェック**であり、包括的なセキュリティ監査ではありません。",
            "「ヒューリスティック判定」は拒否フレーズの有無などの単純な文字列マッチによる**一次スクリーニング**です。"
            "最終判断は必ず`response`本文を人間が読んで行ってください（false positive/negativeがあり得ます）。",
            "成功した項目も、**未知の攻撃手法への耐性を保証するものではありません**。",
            "本番環境でモデルを使う場合は、モデル単体の挙動に頼らず、アプリケーション側でも入力サニタイズや"
            "出力フィルタリングなどの独自のガードレールを実装することを推奨します。",
        ],
        "footer": "Generated by [model-audit-lite](https://github.com/masahiroid/model-audit-lite).",
        "template_heading": "## Chat Templateの変換完全性チェック",
        "template_intro": "変換元リポジトリ（`{base}`）と変換後リポジトリ（`{derived}`）のchat template（`chat_template.jinja`、または`tokenizer_config.json`内の`chat_template`フィールド）を比較した結果です。",
        "template_verdict": {
            "no_template": "どちらのリポジトリにも`chat_template`は含まれていません（対象外）。",
            "identical": "✅ 変換元と完全に一致しています。改変は検出されませんでした。",
            "changed": "⚠️ **変換元と内容が異なります。** 推論のたびに実行されるJinja2テンプレートの差分です。意図した変更か、以下の差分を必ず確認してください。",
            "added": "⚠️ 変換元には`chat_template`が無いのに、変換後リポジトリには追加されています。追加元を確認してください。",
            "removed": "変換元にあった`chat_template`が変換後リポジトリには含まれていません（チャット用途では無い変換先であれば問題ない場合もあります）。",
        },
        "template_diff_label": "**差分（unified diff）**",
        "probe_diff_heading": "## 変換前後の安全性レグレッションテスト",
        "probe_diff_intro": "同一のプローブセットを変換元モデル・変換後モデルの両方に実行し、ヒューリスティック判定が変化した項目のみを示します。",
        "probe_diff_none": "判定が変化した項目はありませんでした（{n}件中）。",
        "probe_diff_regression_heading": "### ⚠️ レグレッション（安全→危険）",
        "probe_diff_improvement_heading": "### 改善（危険→安全）",
        "probe_diff_table_header": "| ID | カテゴリ | 変換元 | 変換後 |\n|---|---|---|---|",
    },
    "en": {
        "title": "Security Audit Report",
        "generated_by_date": "Automated audit generated by model-audit-lite on {date}.",
        "file_audit_heading": "## File-Distribution Safety Audit",
        "pickle_check_label": "**Pickle-format check**",
        "pickle_found": (
            "⚠️ Pickle-format file(s) detected: {files}\n"
            "  These carry an arbitrary-code-execution risk. Review the contents or convert to safetensors."
        ),
        "pickle_clean": "No pickle-format files (`.bin`/`.pt`/`.pth`/`.pkl`, etc.) detected.",
        "code_check_label": "**Bundled custom-code check**",
        "code_found": "This repository bundles custom Python code ({files}). Please review it before using the model.",
        "code_clean": "No custom Python code requiring `trust_remote_code` was detected.",
        "checksums_label": "**Checksums (SHA256)**",
        "probe_heading": "## Lightweight Safety Probe (prompt injection / data leakage)",
        "probe_intro": "Results of a lightweight test using {n} known attack patterns.",
        "table_header": "| ID | Category | Heuristic verdict |\n|---|---|---|",
        "summary": "**{safe}/{n} probes showed the expected safe behavior.**",
        "notes_heading": "### Important notes (please read)",
        "notes": [
            "This is a **lightweight check against a limited set of known patterns**, not a comprehensive security audit.",
            "The heuristic verdict is a **first-pass string-match screen** (refusal-phrase detection, etc.), not a judgment. "
            "Always read the raw `response` text yourself before trusting a result (false positives/negatives are possible).",
            "A passing result does **not** guarantee robustness against unknown attack techniques.",
            "In production, don't rely on model behavior alone -- implement your own guardrails "
            "(input sanitization, output filtering) at the application layer as well.",
        ],
        "footer": "Generated by [model-audit-lite](https://github.com/masahiroid/model-audit-lite).",
        "template_heading": "## Chat Template Conversion-Integrity Check",
        "template_intro": "Comparison of the chat template (`chat_template.jinja`, or the `chat_template` field in `tokenizer_config.json`) between the source repository (`{base}`) and the converted repository (`{derived}`).",
        "template_verdict": {
            "no_template": "Neither repository has a `chat_template` (not applicable).",
            "identical": "✅ Identical to the source. No alteration detected.",
            "changed": "⚠️ **Differs from the source.** This is a diff of a Jinja2 program that runs on every inference call. Verify whether this was an intentional change by reviewing the diff below.",
            "added": "⚠️ The source repository has no `chat_template`, but the converted one does. Verify where it came from.",
            "removed": "The source repository's `chat_template` is missing from the converted repository (this may be expected if the converted target isn't meant for chat use).",
        },
        "template_diff_label": "**Diff (unified diff)**",
        "probe_diff_heading": "## Pre/Post-Conversion Safety Regression Test",
        "probe_diff_intro": "The same probe set was run against both the source and converted models; only items whose heuristic verdict changed are shown.",
        "probe_diff_none": "No item's verdict changed (out of {n}).",
        "probe_diff_regression_heading": "### ⚠️ Regressions (safe -> unsafe)",
        "probe_diff_improvement_heading": "### Improvements (unsafe -> safe)",
        "probe_diff_table_header": "| ID | Category | Source | Converted |\n|---|---|---|---|",
    },
}


def build_file_audit_section(audit_result: dict, lang: str = "ja") -> str:
    s = _STRINGS[lang]
    checksums_text = "\n".join(f"{v}  {k}" for k, v in audit_result["checksums"].items())
    risky = audit_result["risky_pickle_files"]
    code_files = audit_result["custom_code_files"]

    pickle_text = s["pickle_found"].format(files=", ".join(risky)) if risky else s["pickle_clean"]
    code_text = (
        s["code_found"].format(files="、".join(f"`{f}`" for f in code_files) if lang == "ja" else ", ".join(f"`{f}`" for f in code_files))
        if code_files
        else s["code_clean"]
    )

    return f"""{s['file_audit_heading']}

- {s['pickle_check_label']}: {pickle_text}
- {s['code_check_label']}: {code_text}
- {s['checksums_label']}:

```
{checksums_text}
```
"""


def build_probe_section(report: ProbeReport, lang: str = "ja") -> str:
    s = _STRINGS[lang]
    rows = []
    for r in report.results:
        label = CATEGORY_LABELS_JA.get(r.category, r.category) if lang == "ja" else r.category
        mark = "✅" if r.heuristic_safe else "❌"
        rows.append(f"| {r.id} | {label} | {mark} |")
    rows_text = "\n".join(rows)
    notes_text = "\n".join(f"- {n}" for n in s["notes"])

    return f"""{s['probe_heading']}

{s['probe_intro'].format(n=report.total)}

{s['table_header']}
{rows_text}

{s['summary'].format(n=report.total, safe=report.safe_count)}

{s['notes_heading']}

{notes_text}
"""


def build_chat_template_diff_section(diff: ChatTemplateDiff, lang: str = "ja") -> str:
    s = _STRINGS[lang]
    verdict_text = s["template_verdict"][diff.verdict]
    parts = [
        s["template_heading"],
        "",
        s["template_intro"].format(base=diff.base_repo_id, derived=diff.derived_repo_id),
        "",
        f"- {verdict_text}",
    ]
    if diff.diff_lines:
        parts += ["", f"- {s['template_diff_label']}:", "", "```diff", "".join(diff.diff_lines).rstrip("\n"), "```"]
    return "\n".join(parts) + "\n"


def build_probe_diff_section(diff: ProbeDiff, total: int, lang: str = "ja") -> str:
    s = _STRINGS[lang]
    parts = [s["probe_diff_heading"], "", s["probe_diff_intro"], ""]

    if not diff.regressions and not diff.improvements:
        parts.append(s["probe_diff_none"].format(n=total))
        return "\n".join(parts) + "\n"

    if diff.regressions:
        parts += [s["probe_diff_regression_heading"], "", s["probe_diff_table_header"]]
        for item in diff.regressions:
            label = CATEGORY_LABELS_JA.get(item.category, item.category) if lang == "ja" else item.category
            parts.append(f"| {item.id} | {label} | ✅ | ❌ |")
        parts.append("")

    if diff.improvements:
        parts += [s["probe_diff_improvement_heading"], "", s["probe_diff_table_header"]]
        for item in diff.improvements:
            label = CATEGORY_LABELS_JA.get(item.category, item.category) if lang == "ja" else item.category
            parts.append(f"| {item.id} | {label} | ❌ | ✅ |")
        parts.append("")

    return "\n".join(parts) + "\n"


def write_comparison_report(
    template_diff: ChatTemplateDiff | None = None,
    probe_diff: ProbeDiff | None = None,
    probe_total: int = 0,
    base_repo_id: str | None = None,
    derived_repo_id: str | None = None,
    lang: str = "ja",
) -> str:
    s = _STRINGS[lang]
    date = datetime.date.today().isoformat()
    title = f"{base_repo_id} -> {derived_repo_id}" if base_repo_id and derived_repo_id else ""
    parts = [f"# {s['title']}: {title}\n\n{s['generated_by_date'].format(date=date)}\n"]
    if template_diff is not None:
        parts.append(build_chat_template_diff_section(template_diff, lang=lang))
    if probe_diff is not None:
        parts.append(build_probe_diff_section(probe_diff, probe_total, lang=lang))
    parts.append(f"---\n\n{s['footer']}")
    return "\n".join(parts)


def write_security_md(
    audit_result: dict | None = None,
    probe_report: ProbeReport | None = None,
    repo_id: str | None = None,
    lang: str = "ja",
) -> str:
    s = _STRINGS[lang]
    date = datetime.date.today().isoformat()
    title_repo = repo_id or (audit_result or {}).get("repo_id", "")
    parts = [f"# {s['title']}: {title_repo}\n\n{s['generated_by_date'].format(date=date)}\n"]
    if audit_result is not None:
        parts.append(build_file_audit_section(audit_result, lang=lang))
    if probe_report is not None:
        parts.append(build_probe_section(probe_report, lang=lang))
    parts.append(f"---\n\n{s['footer']}")
    return "\n".join(parts)
