"""Regenerate wrappers.yaml from JailbreakBench's published JBC (manual) artifacts.

JailbreakBench ships, under MIT, human-written jailbreak templates (the JBC
"manual" set): one template applied to every benchmark goal. This script fetches
those artifacts and recovers each reusable template by replacing the record's
`goal` with the {behavior} placeholder — so every template string here comes
from the published artifact, transformed by code, not authored in this repo.

    python attack_probes/build_wrappers.py      # writes attack_probes/wrappers.yaml

Source: https://github.com/JailbreakBench/artifacts (MIT).
"""
import json
import urllib.request
from pathlib import Path

RAW_BASE = "https://raw.githubusercontent.com/JailbreakBench/artifacts/main/attack-artifacts/JBC/manual"
SOURCE_MODELS = ("vicuna-13b-v1.5", "llama-2-7b-chat-hf", "gpt-4-0125-preview")
PLACEHOLDER = "{behavior}"
OUT = Path(__file__).resolve().parent / "wrappers.yaml"
HEADER = (
    "# Auto-generated by attack_probes/build_wrappers.py from JailbreakBench JBC\n"
    "# (manual) artifacts, MIT-licensed. Each user_template is a published jailbreak\n"
    "# template with its benchmark goal replaced by the {behavior} placeholder.\n"
    "# Source: https://github.com/JailbreakBench/artifacts\n"
    "# Regenerate with: python attack_probes/build_wrappers.py\n\n"
)


def _template_from_artifact(model: str) -> str | None:
    with urllib.request.urlopen(f"{RAW_BASE}/{model}.json", timeout=30) as response:
        record = json.load(response)["jailbreaks"][0]
    goal, prompt = record.get("goal"), record.get("prompt")
    if not goal or not prompt or goal not in prompt:
        return None
    return prompt.replace(goal, PLACEHOLDER)


def _yaml_block(wrapper_id: str, template: str) -> str:
    body = "\n".join("    " + line for line in template.splitlines())
    return f"- id: {wrapper_id}\n  category: pretext-exercise\n  user_template: |-\n{body}\n"


def main() -> None:
    blocks = []
    for model in SOURCE_MODELS:
        template = _template_from_artifact(model)
        if template:
            blocks.append(_yaml_block(f"jbc-manual-{model}", template))
    OUT.write_text(HEADER + "\n".join(blocks), encoding="utf-8")
    print(f"wrote {OUT} ({len(blocks)} wrappers)")


if __name__ == "__main__":
    main()
